### PR TITLE
001-1

### PR DESCRIPTION
**Pull request by efitzmalcolm**
Further attempts to reconcile Home page appearance

### CODE REVIEW

**Comment by efitzmalcolm** [comment]
Got the Home page looking more like the original Indigo template -- seems like I submitted this Pull Request directly to your Master? Lol, i didn't mean to but I suppose it's more direct than submitting to myself and accepting.

Still working out a few bugs with the appearance but then creating the other objects should go quickly, I'm getting accustomed to the code rules and terms. Can discuss more in a call tomorrow if you have time.

**Comment by nbalauro** [comment]
Hey @efitzmalcolm, I can merge this but -  I don't see any changes?

**Comment by efitzmalcolm** [comment]
Thaaat would be because I didn't commit them locally before I submitted the
pull request, lol.
Sent another just now, let me know if that looks better.

**Comment by nbalauro** [comment]
It looks like you merged all these on your fork after this request. Gonna close it as it appears to duplicate / include same changes as your request from today.

**Pull request closed without merging**
