### PR TITLE
Further branding

### PR DESCRIPTION
**Pull request by efitzmalcolm**
Updates made to colors/layout for footer and links

### CODE REVIEW

**Comment by nbalauro** [comment]
Starting to look good! There are some issues with fluid elements when resizing screen. The footer doesnt seem to handle the resize very well.

Nor the nav bar, we dont want the navbar links to stack on top of each other when downsizing the screen. When they get too close they should change to the select menu. 

Let me know if this is something you want me to look into.

**Comment by nbalauro** [comment]
Also, I think I only like the navbar link boxes to be visible when hovering or when that is the page you are on. Not all the time box border - hover or current page only.

**Comment by efitzmalcolm** [comment]
Hey I made further commits to 006 but it won't let me submit a new pull
request -- is that because the previous one (#23) is still open?

**Comment by efitzmalcolm** [comment]
Oh wait, new commits just push to the open request huh?

**Pull request merged**
